- name: install python
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - python
  tags:
    - python
- name: install nginx
  hosts: all
  become: yes
  roles:
    - nginx
  tags:
    python

